<?php
/** @var \Verideal\VeridealNet\Block\Product $block */
/** @var \Verideal\VeridealNet\ViewModel\FetchVeridealImageBasicData $veridealVm */
?>

<?php
$veridealVm = $block->getVeridealVm();
?>

<?php if ($veridealVm->isVeridealApiEnabled()): ?>
<div class="verideal-button-container">
    <button type="button" disabled id="verideal-display-btn" class="pdp-action-secondary">
        <img src="<?= $block->getViewFileUrl('Verideal_VeridealNet::images/verideal-white.png') ?>" alt="Verideal White Image">
    </button>
</div>
<div id="main-verideal-image-container">
    <div data-bind="scope: 'verideal_image'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>

<script type="text/x-magento-init">
{
     "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "verideal_image": {
                        "component": "Verideal_VeridealNet/js/collect_verideal_image",
                        "config": {
                            "pid": "<?= $block->escapeJs($veridealVm->getProductPid($block->getProduct())) ?>",
                            "token": "<?= $block->escapeJs($veridealVm->getToken()) ?>",
                            "request_url": "<?= $block->escapeJs($veridealVm->getRequestUrl()) ?>"
                        },
                        "template" : "Verideal_VeridealNet/show_verideal_image"
                 }
             }
         }
     }
}
</script>
<?php endif; ?>
